# Generated by Django 4.2 on 2025-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
        ),
        migrations.AddField(
            model_name='toy',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='toys', to='main.tag', verbose_name='Теги'),
        ),
    ]
